name: Build and Push
on: workflow_dispatch

jobs:
  android:
    uses: ./.github/workflows/android.yml
  ios:
    uses: ./.github/workflows/ios.yml
  linux:
    uses: ./.github/workflows/linux.yml
  mac:
    uses: ./.github/workflows/mac.yml
  windows:
    uses: ./.github/workflows/windows.yml
  miscellaneous:
    uses: ./.github/workflows/miscellaneous.yml

  publisher:
    needs: [android, ios, linux, mac, windows, miscellaneous]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.TOKEN }}

      - name: Delete old NDLL's
        run: rm -rf ndll

      - name: Download Android artifact
        uses: actions/download-artifact@v4
        with:
          name: Android
          path: ./ndll/Android

      - name: Download Linux artifact
        uses: actions/download-artifact@v4
        with:
          name: Linux
          path: ./ndll/Linux

      - name: Download Linux64 artifact
        uses: actions/download-artifact@v4
        with:
          name: Linux64
          path: ./ndll/Linux64

      - name: Download LinuxArm artifact
        uses: actions/download-artifact@v4
        with:
          name: LinuxArm
          path: ./ndll/LinuxArm

      - name: Download LinuxArm64 artifact
        uses: actions/download-artifact@v4
        with:
          name: LinuxArm64
          path: ./ndll/LinuxArm64

      - name: Download Mac64 artifact
        uses: actions/download-artifact@v4
        with:
          name: Mac64
          path: ./ndll/Mac64

      - name: Download MacArm64 artifact
        uses: actions/download-artifact@v4
        with:
          name: MacArm64
          path: ./ndll/MacArm64

      - name: Download Miscellaneous artifact
        uses: actions/download-artifact@v4
        with:
          name: Miscellaneous
          path: .

      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: Windows
          path: ./ndll/Windows

      - name: Download Windows64 artifact
        uses: actions/download-artifact@v4
        with:
          name: Windows64
          path: ./ndll/Windows64

      - name: Download WindowsArm64 artifact
        uses: actions/download-artifact@v4
        with:
          name: WindowsArm64
          path: ./ndll/WindowsArm64

      - name: Download iPhone artifact
        uses: actions/download-artifact@v4
        with:
          name: iPhone
          path: ./ndll/iPhone

      - name: Push to GitHub
        uses: stefanzweifel/git-auto-commit-action@v5.0.1
        with:
          commit_message: "Builded and Pushed New NDLL's."
        env:
          GH_TOKEN: ${{ secrets.TOKEN }}