name: Build and Push
on: workflow_dispatch

jobs:
  android:
    uses: ./.github/workflows/android.yml
  ios:
    uses: ./.github/workflows/ios.yml
  linux:
    uses: ./.github/workflows/linux.yml
  mac:
    uses: ./.github/workflows/mac.yml
  windows:
    uses: ./.github/workflows/windows.yml

  publisher:
    needs: [android, ios, linux, mac, windows]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.TOKEN }}

      - name: Delete old NDLL's
        run: rm -rf ndll

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ${{ github.workspace }}/ndll

      - name: Push to GitHub
        uses: stefanzweifel/git-auto-commit-action@v5.0.1
        with:
          commit_message: "Builded and Pushed New NDLL's."
        env:
          GH_TOKEN: ${{ secrets.TOKEN }}
