name: Mac CI
on:
  workflow_dispatch:
  workflow_call:

env:
  HAXE_VERSION: 4.3.6

jobs:
  mac:
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: ${{ env.HAXE_VERSION }}
      - name: Set HAXEPATH
        run: echo "HAXEPATH=$HAXE_STD_PATH/.." >> $GITHUB_ENV
      - name: Install Haxe dependencies
        run: |
          haxelib git hxcpp https://github.com/mcagabe19-stuff/hxcpp --quiet
          haxelib install format --quiet
          haxelib install hxp --quiet
      - name: Enable HXCPP compile cache
        run: echo "HXCPP_COMPILE_CACHE=~/.hxcpp" >> $GITHUB_ENV
      - name: Configure Lime
        run: haxelib dev lime ${{ github.workspace }}
      - name: Rebuild Lime
        run: |
          # haxelib run lime rebuild mac -32 -release -nocolor -nocffi -eval
          haxelib run lime rebuild mac -64 -release -nocolor -nocffi -eval
      # - name: Upload Artifact (x86)
        # uses: actions/upload-artifact@v3
        # with:
          # name: Mac
          # path: |
            # ndll/Mac/
            # !**/.gitignore
          # if-no-files-found: error
      - name: Upload Artifact (x86_64)
        uses: actions/upload-artifact@v3
        with:
          name: Mac64
          path: |
            ndll/Mac64/
            !**/.gitignore
          if-no-files-found: error
  macarm64:
    runs-on: macos-15
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: ${{ env.HAXE_VERSION }}
      - name: Set HAXEPATH
        run: echo "HAXEPATH=$HAXE_STD_PATH/.." >> $GITHUB_ENV
      - name: Install Haxe dependencies
        run: |
          haxelib git hxcpp https://github.com/mcagabe19-stuff/hxcpp --quiet
          haxelib install format --quiet
          haxelib install hxp --quiet
      - name: Enable HXCPP compile cache
        run: echo "HXCPP_COMPILE_CACHE=~/.hxcpp" >> $GITHUB_ENV
      - name: Configure Lime
        run: haxelib dev lime ${{ github.workspace }}
      - name: Rebuild Lime
        run: haxelib run lime rebuild mac -arm64 -release -nocolor -nocffi -eval -D HXCPP_ARM64
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: MacArm64
          path: |
            ndll/MacArm64/
            !**/.gitignore
          if-no-files-found: error
